### ISSUE TITLE
Evaluación Mercado Liebre - Martin Atia 

### ISSUE THREAD

**Issue by martinatia** [AynelenLedesma/MercadoLiebre#1]
- [x] 1 Cumple
- [x] 2 Cumple
- [x] #2
- [x] 4 Cumple
- [x] 5 Cumple
- [x] 6 Cumple
- [x] 7 Cumple
- [x] 8 Los iconos del footer si (aunque el color es el mismo!), pero no tiene animación del camión y tampoco aparece/desaparece la descripción de los productos.
- [x] 9 Cosas que me gustan: El estilo de los formularios de login y registración
- [x] 10 Mejoras: Cambiarle el estilo de los textos de los navbar, ajustar bien el tamaño de la barra de búsqueda del header, en especial cuando se agranda la resolución (aparece por momentos muy grande)

**Comment by AynelenLedesma** [comment]
El dispositivo hamburguesa no se muestra para pc, y si para cel y tablet mini. De acuerdo con resto, lo de los colores solo porque quería usar colores que nos habían pedido, puse un azul y celeste, pero no se diferencia bien.
